import { faPenFancy } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { client } from "../lib/client";

export default function Home({ blog }) {
  return (
    <section className="text-gray-600 body-font">
    <div className="container px-5 py-24 mx-auto">

        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        </Head>

    
    <div>
      <ul>
        {blog.map((blog) => (
          <li key={blog.id}>
            <Link href={`/blog/${blog.id}`}>
              <a className="title-font text-2xl mt-6 mb-3 font-medium text-gray-900">
              <FontAwesomeIcon icon={faPenFancy} className="mr-2"/>
              {blog.title}
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
    </div>
    </section>
  );
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blog" });

  return {
    props: {
      blog: data.contents,
    },
  };
};