import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import Image from 'next/image'
import profilePic from '../public/sample.jpeg'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBookOpen, faEnvelope, faHeart, faImages, faPaperPlane } from '@fortawesome/free-solid-svg-icons'
import { useAuthentication } from '../hooks/authentication'

export default function Home() {
  const { user } = useAuthentication()
  return (
    <section className="text-gray-600 body-font">
    <div className="container px-5 py-24 mx-auto">

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <div className="flex flex-wrap -mx-4 -mb-10">
      <div className="sm:w-1/2 mb-10 px-4 .text-left">
        <div className="rounded-lg overflow-hidden">
          <Image alt="content" className="object-cover object-center h-full w-full" src={profilePic} />
        </div>
        <h3 className="title-font text-2xl font-medium text-gray-900 mt-6 mb-3"><FontAwesomeIcon icon={faBookOpen} className="mr-2"/>展示　8p R18</h3>
        <p className="w-2/3 leading-relaxed text-base">・最中にきざなこと言う南城とそれに弱い薫が描きたかった</p>
        <p className="w-2/3 leading-relaxed text-base">・攻めが中途半端にパンツ履いたままなの好きです…</p>
        <p className="w-2/3 leading-relaxed text-base">・勢いで描いたのでふわっと読んでください</p>
        <p className="w-2/3 leading-relaxed text-base">PASS：</p>
        <p className="w-2/3 leading-relaxed text-base">※18歳未満の方の閲覧はお断りしています</p>
        <button className="mt-6 bg-blue-400 text-white active:bg-lightBlue-200 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button"><a href="https://poipiku.com/2542277/">ぽいぴく</a></button>
      </div>
      <div className="sm:w-1/2 flex flex-col mb-10 px-4 .text-left">
      <div>
      <p className="leading-relaxed text-base"><FontAwesomeIcon icon={faEnvelope} className="mr-2"/>なにかありましたらスペースのメッセージボードかこちらにお願いします！</p>
        <button className="mt-6 bg-rose-300 text-white active:bg-rose-200 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button"><a href="https://marshmallow-qa.com/mocha_sk?utm_medium=url_text&utm_source=promotion">マシュマロ</a></button>
      </div>
      <div className="mt-8">
      <p className="leading-relaxed text-base"><FontAwesomeIcon icon={faImages} className="mr-2"/>ときどき絵をかきます</p>
        <button className="mt-6 bg-sky-400 text-white active:bg-lightBlue-200 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" type="button"><a href="https://twitter.com/mocha_sk">twitter</a></button>
      </div>
      </div>
    </div>

</div>
  </section>
  )
}
